package Controller;

import javafx.fxml.FXML;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import application.Model;
import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;
import javafx.stage.Stage;

public class verifyBookController {
	@FXML
	private TextArea text;
	private String cl;
	private String id;
	private Model model = new Model();
	private Connection myConn = model.connect("sa", "bob1234");
	
	public void setScene() {
		ResultSet q = model.getData(myConn,"F.FLIGHT_NUMBER,F.DEPARTURE_COUNTRY,F.ARRIVAL_COUNTRY,F.DEPARTURE_TIME,F.ARRIVAL_TIME,MAX(R.SEAT_NUMBER) AS MAX_SEAT", "FLIGHT F,RESERVATION R", "F.FLIGHT_NUMBER='"+id+"' AND R.FID=F.FLIGHT_NUMBER AND R.CLASS = '"+cl+"' GROUP BY F.FLIGHT_NUMBER,F.DEPARTURE_COUNTRY,F.ARRIVAL_COUNTRY,F.DEPARTURE_TIME,F.ARRIVAL_TIME");
		try {
			if(q.next()) {
					text.setText("You are going to book the flight "+q.getString("FLIGHT_NUMBER").trim()+" going from "+q.getString("DEPARTURE_COUNTRY").trim()+" to "+q.getString("ARRIVAL_COUNTRY").trim()
						+".The flight time is from "+q.getString("DEPARTURE_TIME").trim()+" till "+q.getString("ARRIVAL_TIME").trim()+".And your seat number is "+String.valueOf(q.getInt("MAX_SEAT")+1)+" in the "+cl+" class.We wish you a safe flight :)");
			}else {
				q = model.getData(myConn,"*", "FLIGHT F", "F.FLIGHT_NUMBER='"+id+"'");
				if(q.next()) {
					if(cl.equalsIgnoreCase("first")) {
						text.setText("You are going to book the flight "+q.getString("FLIGHT_NUMBER").trim()+" going from "+q.getString("DEPARTURE_COUNTRY").trim()+" to "+q.getString("ARRIVAL_COUNTRY").trim()
						+".The flight time is from "+q.getString("DEPARTURE_TIME").trim()+" till "+q.getString("ARRIVAL_TIME").trim()+".And your seat number is 1 in the "+cl+" class.We wish you a safe flight :)");
					}else if(cl.equalsIgnoreCase("business")) {
						text.setText("You are going to book the flight "+q.getString("FLIGHT_NUMBER").trim()+" going from "+q.getString("DEPARTURE_COUNTRY").trim()+" to "+q.getString("ARRIVAL_COUNTRY").trim()
						+".The flight time is from "+q.getString("DEPARTURE_TIME").trim()+" till "+q.getString("ARRIVAL_TIME").trim()+".And your seat number is 11 in the "+cl+" class.We wish you a safe flight :)");
					}else if(cl.equalsIgnoreCase("economy")) {
						text.setText("You are going to book the flight "+q.getString("FLIGHT_NUMBER").trim()+" going from "+q.getString("DEPARTURE_COUNTRY").trim()+" to "+q.getString("ARRIVAL_COUNTRY").trim()
						+".The flight time is from "+q.getString("DEPARTURE_TIME").trim()+" till "+q.getString("ARRIVAL_TIME").trim()+".And your seat number is 41 in the "+cl+" class.We wish you a safe flight :)");
					}
					
				}
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void book(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage)text.getScene().getWindow();
		stage.setUserData("True");
		stage.close();
		
	}
	public void setValues(String cl,String id) {
		this.cl = cl;
		this.id = id;
	}
}
